package MyServer.MyServicePackage;


/**
* MyServer/MyServicePackage/unknown_customerID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/prachi/workspace/DRS.Project/simple.idl
* Friday, November 30, 2012 5:50:25 PM EST
*/

public final class unknown_customerID extends org.omg.CORBA.UserException
{

  public unknown_customerID ()
  {
    super(unknown_customerIDHelper.id());
  } // ctor


  public unknown_customerID (String $reason)
  {
    super(unknown_customerIDHelper.id() + "  " + $reason);
  } // ctor

} // class unknown_customerID
