package MyServer.MyServicePackage;


/**
* MyServer/MyServicePackage/unknown_customerIDHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/prachi/workspace/DRS.Project/simple.idl
* Friday, November 30, 2012 5:50:25 PM EST
*/

abstract public class unknown_customerIDHelper
{
  private static String  _id = "IDL:MyServer/MyService/unknown_customerID:1.0";

  public static void insert (org.omg.CORBA.Any a, MyServer.MyServicePackage.unknown_customerID that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static MyServer.MyServicePackage.unknown_customerID extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [0];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (MyServer.MyServicePackage.unknown_customerIDHelper.id (), "unknown_customerID", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static MyServer.MyServicePackage.unknown_customerID read (org.omg.CORBA.portable.InputStream istream)
  {
    MyServer.MyServicePackage.unknown_customerID value = new MyServer.MyServicePackage.unknown_customerID ();
    // read and discard the repository ID
    istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, MyServer.MyServicePackage.unknown_customerID value)
  {
    // write the repository ID
    ostream.write_string (id ());
  }

}
