package MyServer.MyServicePackage;

/**
* MyServer/MyServicePackage/unknown_customerIDHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/prachi/workspace/DRS.Project/simple.idl
* Friday, November 30, 2012 5:50:25 PM EST
*/

public final class unknown_customerIDHolder implements org.omg.CORBA.portable.Streamable
{
  public MyServer.MyServicePackage.unknown_customerID value = null;

  public unknown_customerIDHolder ()
  {
  }

  public unknown_customerIDHolder (MyServer.MyServicePackage.unknown_customerID initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MyServer.MyServicePackage.unknown_customerIDHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MyServer.MyServicePackage.unknown_customerIDHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MyServer.MyServicePackage.unknown_customerIDHelper.type ();
  }

}
