package MyServer;


/**
* MyServer/MyServicePOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/prachi/workspace/DRS.Project/simple.idl
* Friday, November 30, 2012 5:50:25 PM EST
*/

public class MyServicePOATie extends MyServicePOA
{

  // Constructors

  public MyServicePOATie ( MyServer.MyServiceOperations delegate ) {
      this._impl = delegate;
  }
  public MyServicePOATie ( MyServer.MyServiceOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public MyServer.MyServiceOperations _delegate() {
      return this._impl;
  }
  public void _delegate (MyServer.MyServiceOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public String itemReturned (String customerID, int itemID, int noOfReturnedItem) throws MyServer.MyServicePackage.unknown_customerID
  {
    return _impl.itemReturned(customerID, itemID, noOfReturnedItem);
  } // itemReturned

  public String buy (String customerID, int itemID, int numberOfItem) throws MyServer.MyServicePackage.unknown_customerID
  {
    return _impl.buy(customerID, itemID, numberOfItem);
  } // buy

  public String exchange (String customerID, int boughtItemID, int boughtNumber, int desiredItemID, int desiredNumber) throws MyServer.MyServicePackage.unknown_customerID
  {
    return _impl.exchange(customerID, boughtItemID, boughtNumber, desiredItemID, desiredNumber);
  } // exchange

  public String checkStock (String customerID, int itemID) throws MyServer.MyServicePackage.unknown_customerID
  {
    return _impl.checkStock(customerID, itemID);
  } // checkStock

  private MyServer.MyServiceOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class MyServicePOATie
