package MyServer;


/**
* MyServer/MyServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/prachi/workspace/DRS.Project/simple.idl
* Friday, November 30, 2012 5:50:25 PM EST
*/

public interface MyServiceOperations 
{
  String itemReturned (String customerID, int itemID, int noOfReturnedItem) throws MyServer.MyServicePackage.unknown_customerID;
  String buy (String customerID, int itemID, int numberOfItem) throws MyServer.MyServicePackage.unknown_customerID;
  String exchange (String customerID, int boughtItemID, int boughtNumber, int desiredItemID, int desiredNumber) throws MyServer.MyServicePackage.unknown_customerID;
  String checkStock (String customerID, int itemID) throws MyServer.MyServicePackage.unknown_customerID;
} // interface MyServiceOperations
