package MyServer;


/**
* MyServer/MyServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/prachi/workspace/DRS.Project/simple.idl
* Friday, November 30, 2012 5:50:25 PM EST
*/

public abstract class MyServicePOA extends org.omg.PortableServer.Servant
 implements MyServer.MyServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("itemReturned", new java.lang.Integer (0));
    _methods.put ("buy", new java.lang.Integer (1));
    _methods.put ("exchange", new java.lang.Integer (2));
    _methods.put ("checkStock", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MyServer/MyService/itemReturned
       {
         try {
           String customerID = in.read_string ();
           int itemID = in.read_long ();
           int noOfReturnedItem = in.read_long ();
           String $result = null;
           $result = this.itemReturned (customerID, itemID, noOfReturnedItem);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (MyServer.MyServicePackage.unknown_customerID $ex) {
           out = $rh.createExceptionReply ();
           MyServer.MyServicePackage.unknown_customerIDHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // MyServer/MyService/buy
       {
         try {
           String customerID = in.read_string ();
           int itemID = in.read_long ();
           int numberOfItem = in.read_long ();
           String $result = null;
           $result = this.buy (customerID, itemID, numberOfItem);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (MyServer.MyServicePackage.unknown_customerID $ex) {
           out = $rh.createExceptionReply ();
           MyServer.MyServicePackage.unknown_customerIDHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // MyServer/MyService/exchange
       {
         try {
           String customerID = in.read_string ();
           int boughtItemID = in.read_long ();
           int boughtNumber = in.read_long ();
           int desiredItemID = in.read_long ();
           int desiredNumber = in.read_long ();
           String $result = null;
           $result = this.exchange (customerID, boughtItemID, boughtNumber, desiredItemID, desiredNumber);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (MyServer.MyServicePackage.unknown_customerID $ex) {
           out = $rh.createExceptionReply ();
           MyServer.MyServicePackage.unknown_customerIDHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // MyServer/MyService/checkStock
       {
         try {
           String customerID = in.read_string ();
           int itemID = in.read_long ();
           String $result = null;
           $result = this.checkStock (customerID, itemID);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (MyServer.MyServicePackage.unknown_customerID $ex) {
           out = $rh.createExceptionReply ();
           MyServer.MyServicePackage.unknown_customerIDHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MyServer/MyService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public MyService _this() 
  {
    return MyServiceHelper.narrow(
    super._this_object());
  }

  public MyService _this(org.omg.CORBA.ORB orb) 
  {
    return MyServiceHelper.narrow(
    super._this_object(orb));
  }


} // class MyServicePOA
