package Client;
/*
 * The client implementation is generated by the ORB Studio.
 */
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.LineNumberReader;
import java.util.Properties;

class ClientImpl {
	private MyServer.MyService target = null;
	private org.omg.CORBA.ORB orb = null;

	/**
	 * Constructor for ClientImpl
	 * 
	 * @throws IOException
	 */
	public ClientImpl() throws IOException 
	{
		initORB(null);
	}

	/**
	 * Constructor for ClientImpl
	 * 
	 * @throws IOException
	 * @see java.lang.Object#Object()
	 */
	public ClientImpl(String[] args) throws IOException
	{
		initORB(args);
	}

	/**
	 * Initialize ORB.
	 *  
	 * @param args
	 * @throws IOException
	 */
	public void initORB(String[] args) throws IOException
	{

		Properties props = System.getProperties();
		props.setProperty("org.omg.CORBA.ORBClass", "com.sun.corba.se.internal.POA.POAORB");
		props.setProperty("org.omg.CORBA.ORBSingletonClass", "com.sun.corba.se.internal.corba.ORBSingleton");

		// Initialize the ORB
		orb = org.omg.CORBA.ORB.init((String[])args, props);

		// ---- Uncomment below to enable Naming Service access. ----
		// org.omg.CORBA.Object ncobj = orb.resolve_initial_references("NameService");
		// NamingContextExt nc = NamingContextExtHelper.narrow(ncobj);
		// org.omg.CORBA.Object obj = nc.resolve_str("MyServerObject");

		LineNumberReader input = new LineNumberReader(new FileReader("C:\\Users\\prachi\\workspace\\DRS.Project\\server.ior"));
		String ior = input.readLine();
		org.omg.CORBA.Object obj = orb.string_to_object(ior);

		target = MyServer.MyServiceHelper.narrow(obj);		
	}

	/**
	 * Obtain ORB Interface.
	 * 
	 * @return
	 */
	public MyServer.MyService getORBInterface()
	{
		return target;
	}

	/**
	 * Shutdown ORB.
	 */
	public void shutdown()
	{
		orb.shutdown(true);
	}
	/**
	 * Test driver for RetailStoreOperationClientImpl.
	 * 
	 * @param args
	 */
	public static void main(String[] args) 
	{
		try
		{
			
			ClientImpl test = new ClientImpl();
												
			BufferedReader stdin = new BufferedReader(new InputStreamReader(System.in));			
			String customerID = "";	 
			String command = "";
			int itemID = 0;		
			String msg = "";
			int numberOfItem = 0;
			if(args[0].equalsIgnoreCase("Interactive"))
            {	
				while(true)
	            {
	      		 try{
		            	boolean flag = true;
		            	System.out.println("\n Enter your Customer ID:");
		            	customerID = stdin.readLine();
		            	if(customerID.equalsIgnoreCase("x"))
		    	      	{      	
		            		flag = false;
		    	      		System.exit(1);
		    	      	}		    	      
			            while(flag)
			            {
				            System.out.println("\nClient Interface");
				            System.out.println("\nSelect Opertation to Perform:");
				            System.out.println("\n 1. Buy an Item");
				            System.out.println("\n 2. Return an Item");
				            System.out.println("\n 3. Check Stock for an Item");
				            System.out.println("\n 4. Exchange an Item");
				            System.out.println("\n 5. Exit");
				            System.out.println("\n Enter your choice:");
				            command = stdin.readLine();
				            command = command.trim();				            
				            
				            switch(command)
				            {
				              case "1" :		            	  
				            	  System.out.println("\n Enter the Item ID of item you want to buy:");
				            	  itemID = Integer.parseInt(stdin.readLine());
				            	  System.out.println("\n Enter the number of Items you want to buy:");
				            	  numberOfItem = Integer.parseInt(stdin.readLine());		            	  	 			            	  	 			            	 
				            	  msg = test.getORBInterface().buy(customerID, itemID, numberOfItem);
				            	  System.out.println("\nMessage:"+msg);	 			            	  
				            	  break;
				              case "2":		            	  
				            	  System.out.println("\n Enter the Item ID of item you want to return:");
				            	  itemID = Integer.parseInt(stdin.readLine());
				            	  System.out.println("\n Enter the number of Items you want to return:");
				            	  numberOfItem = Integer.parseInt(stdin.readLine());		            	  
				            	  msg = test.getORBInterface().itemReturned(customerID, itemID, numberOfItem);  			            	  			            	  
				    			  System.out.println("\nMessage: "+msg);	 			    			  
				            	  break;
				              case "3" :		            	  
				            	  System.out.println("\n\t Enter the Item ID of item for which you want to check the stock:");
				            	  itemID = Integer.parseInt(stdin.readLine());		            	  
				            	  String resultString = "";					            	  
				            	  resultString = test.getORBInterface().checkStock(customerID,itemID);					            	  	 			            	  
	 			                  System.out.println(resultString);				                  
				            	  break;
				              case "4" :
				            	   // perform exchange operation 
				            	  System.out.println("\n\t Enter the Item ID of item which you want to return:");
				            	  itemID = Integer.parseInt(stdin.readLine());
				            	  System.out.println("\n Enter the number of Items you want to return:");
				            	  numberOfItem = Integer.parseInt(stdin.readLine());	
				            	  System.out.println("\n\t Enter the Item ID of item which you want to buy against the return:");
				            	  int desiredItemID = Integer.parseInt(stdin.readLine());
				            	  System.out.println("\n Enter the number of Items you want to buy against the return:");
				            	  int desiredNumber = Integer.parseInt(stdin.readLine());
				            	   msg = test.getORBInterface().exchange(customerID, itemID, numberOfItem, desiredItemID, desiredNumber);
				            	   System.out.println("\nMessage: "+msg);
				            	   break;
				              case "5" :
				            	   flag= false;
				            	   break;
				              default:
				            	   System.out.println("\nInvalid choice.Please enter the choice again.");
				            	   break;
				            }		            
			            }	 
	      		 }
	      		 catch(Exception e)
	      		 {
	      			 e.printStackTrace();
	      			try {
						Thread.sleep(30000);
					} catch (InterruptedException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					}
	      		 }
	            }
            }
			else if(args[0].equalsIgnoreCase("Debug"))
            {
				try
				{
					command = args[1];
			        command = command.trim();
			        customerID = args[2]; 						    	      	           			            			           
			            switch(command)
			            {
			              case "1" :		            	  			            	  
			            	  itemID = Integer.parseInt(args[3]);			            	  
			            	  numberOfItem = Integer.parseInt(args[4]);		            	  	 			            	  	 			            	 
			            	  msg = test.getORBInterface().buy(customerID, itemID, numberOfItem);
			            	  System.out.println("\nMessage:"+msg);	 	
			            	  Thread.sleep(30000);
			            	  break;
			              case "2":		            	  			            	  
			            	  itemID = Integer.parseInt(args[3]);			            	  
			            	  numberOfItem = Integer.parseInt(args[4]);		            	  
			            	  msg = test.getORBInterface().itemReturned(customerID, itemID, numberOfItem);  			            	  			            	  
			    			  System.out.println("\nMessage: "+msg);
			    			  Thread.sleep(30000);
			            	  break;
			              case "3" :		            	  			            	  
			            	  itemID = Integer.parseInt(args[3]);		            	  
			            	  String resultString = "";					            	  
			            	  resultString = test.getORBInterface().checkStock(customerID,itemID);					            	  	 			            	  
 			                  System.out.println(resultString);	
 			                 Thread.sleep(30000);
			            	  break;
			              case "4" :
			            	   // perform exchange operation 			            	  
			            	  itemID = Integer.parseInt(args[3]);			            	  
			            	  numberOfItem = Integer.parseInt(args[4]);				            	  
			            	  int desiredItemID = Integer.parseInt(args[5]);			            	  
			            	  int desiredNumber = Integer.parseInt(args[6]);
			            	   msg = test.getORBInterface().exchange(customerID, itemID, numberOfItem, desiredItemID, desiredNumber);
			            	   System.out.println("\nMessage: "+msg);
			            	   Thread.sleep(30000);
			            	   break;
			              case "5" :			            	   
			            	   break;
			              default:
			            	   System.out.println("\nInvalid choice.Please enter the choice again.");
			            	   break;			            	           
		             }	 																            	 			      			          			          
				}
				catch(Exception e)
				{
					e.printStackTrace();
					try {
						Thread.sleep(30000);
					} catch (InterruptedException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					}
	            }		    	      	 
		            
	          }	      		      		      		      		      		      		      								        	  	                
			//test.shutdown();		
		}
		catch(Exception e)
		{
			e.printStackTrace();
		}
	}
}
